// Package otel provides a Gravix span exporter for OpenTelemetry.
//
// The exporter converts completed HTTP spans into Gravix RequestFact records
// and sends them via the Gravix client. Non-HTTP spans are silently skipped.
//
// Usage:
//
//	client := gravix.New("http://localhost:8090", "my-api-key", gravix.WithService("my-svc"))
//	exporter := otel.NewExporter(client)
//	tp := sdktrace.NewTracerProvider(sdktrace.WithBatcher(exporter))
//	otelapi.SetTracerProvider(tp)
package otel

import (
	"context"
	"strconv"

	gravix "github.com/gravix-io/gravix-go"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	sdktrace "go.opentelemetry.io/otel/sdk/trace"
)

// semconv attribute keys (stable HTTP semantic conventions).
const (
	attrHTTPMethod         = "http.method"
	attrHTTPRoute          = "http.route"
	attrHTTPStatusCode     = "http.status_code"
	attrHTTPRequestMethod  = "http.request.method"  // newer semconv
	attrHTTPResponseStatus = "http.response.status_code" // newer semconv
	attrHTTPTarget         = "http.target"
	attrUserAgentOriginal  = "user_agent.original"
	attrHTTPUserAgent      = "http.user_agent"
)

// Exporter implements sdktrace.SpanExporter by converting HTTP spans
// into Gravix RequestFact records and sending them via the Gravix client.
type Exporter struct {
	client *gravix.Client
}

// NewExporter creates a new Gravix OpenTelemetry span exporter.
func NewExporter(client *gravix.Client) *Exporter {
	return &Exporter{client: client}
}

// ExportSpans converts completed spans to Gravix facts and records them.
// Non-HTTP spans (those without http.method or http.request.method) are skipped.
func (e *Exporter) ExportSpans(ctx context.Context, spans []sdktrace.ReadOnlySpan) error {
	for _, span := range spans {
		fact, ok := spanToFact(span)
		if !ok {
			continue // not an HTTP span
		}
		if err := e.client.RecordFact(ctx, fact); err != nil {
			return err
		}
	}
	return nil
}

// Shutdown flushes any remaining facts in the Gravix client.
func (e *Exporter) Shutdown(ctx context.Context) error {
	return e.client.Flush(ctx)
}

// spanToFact converts an OTel span to a Gravix RequestFact.
// Returns false if the span is not an HTTP span.
func spanToFact(span sdktrace.ReadOnlySpan) (gravix.RequestFact, bool) {
	attrs := attrMap(span.Attributes())

	// Determine HTTP method — try both old and new semconv keys.
	method := attrString(attrs, attrHTTPRequestMethod)
	if method == "" {
		method = attrString(attrs, attrHTTPMethod)
	}
	if method == "" {
		return gravix.RequestFact{}, false // not an HTTP span
	}

	// Status code — try new semconv first.
	statusCode := attrInt(attrs, attrHTTPResponseStatus)
	if statusCode == 0 {
		statusCode = attrInt(attrs, attrHTTPStatusCode)
	}
	// If still 0 and span has an error status, use 500.
	if statusCode == 0 && span.Status().Code == codes.Error {
		statusCode = 500
	}

	// Path template — prefer http.route, fall back to http.target.
	pathTemplate := attrString(attrs, attrHTTPRoute)
	if pathTemplate == "" {
		pathTemplate = attrString(attrs, attrHTTPTarget)
	}
	if pathTemplate == "" {
		pathTemplate = "/" + span.Name()
	}

	// User agent.
	ua := attrString(attrs, attrUserAgentOriginal)
	if ua == "" {
		ua = attrString(attrs, attrHTTPUserAgent)
	}

	// Latency from span duration.
	latencyMs := int(span.EndTime().Sub(span.StartTime()).Milliseconds())

	return gravix.RequestFact{
		// EventID and EventTime will be auto-generated by the client.
		Method:          method,
		PathTemplate:    pathTemplate,
		StatusCode:      statusCode,
		LatencyMs:       latencyMs,
		UserAgentFamily: ua,
	}, true
}

// attrMap converts a slice of key-value attributes to a map for fast lookup.
func attrMap(attrs []attribute.KeyValue) map[string]attribute.Value {
	m := make(map[string]attribute.Value, len(attrs))
	for _, kv := range attrs {
		m[string(kv.Key)] = kv.Value
	}
	return m
}

// attrString returns the string value for a key, or empty string.
func attrString(m map[string]attribute.Value, key string) string {
	v, ok := m[key]
	if !ok {
		return ""
	}
	if v.Type() == attribute.STRING {
		return v.AsString()
	}
	return ""
}

// attrInt returns the int value for a key, or 0.
func attrInt(m map[string]attribute.Value, key string) int {
	v, ok := m[key]
	if !ok {
		return 0
	}
	switch v.Type() {
	case attribute.INT64:
		return int(v.AsInt64())
	case attribute.STRING:
		n, _ := strconv.Atoi(v.AsString())
		return n
	default:
		return 0
	}
}
