#!/usr/bin/env python3
# Copyright 2026 The Gravix Authors
# SPDX-License-Identifier: Apache-2.0
"""Generates the public roadmap board from the documents that already decide it.

The board is generated rather than written so that it cannot quietly disagree
with the goal tree, the spec index or the non-goals. `make roadmap-check` fails
when the committed board differs from a fresh generation, which makes a stale
roadmap a red build rather than something a reader finds out the hard way.

It publishes no dates. Phase durations in the roadmap are estimates, and an
estimate published as a commitment produces one kind of feedback and no useful
planning — so a date reaching the output is a generation failure, not a warning.

Usage:
  scripts/gen_roadmap_board.py [--out PATH] [--input-json PATH] [--check]
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass, field

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GOAL_TREE = os.path.join(ROOT, "docs", "oss", "12-goal-tree.md")
SPEC_INDEX = os.path.join(ROOT, "docs", "oss", "specs", "SPEC-INDEX.md")
NON_GOALS = os.path.join(ROOT, "docs", "04-non-goals.md")
ROADMAP = os.path.join(ROOT, "docs", "oss", "20-roadmap-horizon-2.md")
DEFAULT_OUT = os.path.join(ROOT, "docs-site", "docs", "roadmap.md")

GENERATED_MARKER = "<!-- GENERATED by scripts/gen_roadmap_board.py — do not edit -->"

# An input may sit undecided for at most two goal reviews. Indefinite
# consideration is a decline that nobody has to defend.
MAX_TICKS_UNDER_CONSIDERATION = 2

DISPOSITION_DEFAULT = "under consideration"
DISPOSITION_PATTERNS = (
    re.compile(r"^under consideration$", re.I),
    re.compile(r"^accepted as SPEC GRVX-\d{3,4}$", re.I),
    re.compile(r"^declined — non-goal §[1-7]$", re.I),
    re.compile(r"^declined — .+$", re.I),
)

# Anything that reads as a delivery date. Phase numbers and spec ids are not
# dates and must not trip this.
DATE_PATTERNS = re.compile(
    r"\b(20\d{2}-\d{2}(-\d{2})?"
    r"|Q[1-4]\s+20\d{2}"
    r"|(January|February|March|April|May|June|July|August|September|October|November|December)\s+20\d{2}"
    r"|\b20\d{2}\b)",
)


class GenerationError(Exception):
    """A board that cannot be generated honestly is not generated at all."""


@dataclass
class Spec:
    spec_id: str
    title: str
    placement: str
    goal: str


@dataclass
class Phase:
    number: int
    theme: str
    goal: str
    specs: list[Spec] = field(default_factory=list)


@dataclass
class NonGoal:
    number: int
    title: str
    refusals: list[str]
    alternative: str


@dataclass
class Input:
    number: int
    title: str
    disposition: str
    ticks: int


def read(path: str) -> str:
    with open(path, encoding="utf-8") as f:
        return f.read()


# --- parsing ---------------------------------------------------------------


def parse_phases(text: str) -> list[Phase]:
    """Reads the per-phase spec tables out of the generated spec index."""
    phases: list[Phase] = []
    current: Phase | None = None

    heading = re.compile(r"^## Phase (\d+) — (.+?)\s*$")
    goal_line = re.compile(r"^\*\*Goal:\*\*\s*(\S+)")
    row = re.compile(r"^\|\s*\[(GRVX-\d{3,4})\]\([^)]*\)\s*\|\s*(.+?)\s*\|\s*`?(\w+)`?\s*\|\s*([^|]*?)\s*\|")

    for line in text.splitlines():
        m = heading.match(line)
        if m:
            current = Phase(number=int(m.group(1)), theme=m.group(2).strip(), goal="")
            phases.append(current)
            continue
        if current is None:
            continue
        m = goal_line.match(line)
        if m:
            current.goal = m.group(1)
            continue
        m = row.match(line)
        if m:
            current.specs.append(
                Spec(spec_id=m.group(1), title=m.group(2).strip(),
                     placement=m.group(3), goal=m.group(4).strip())
            )

    if not phases:
        raise GenerationError("roadmap: the spec index has no phase tables")
    return phases


def parse_non_goals(text: str) -> list[NonGoal]:
    """Reads the seven non-goals, each of which must name an alternative tool."""
    out: list[NonGoal] = []
    heading = re.compile(r"^## (\d+)\. (.+?)\s*$")
    alt = re.compile(r"^- \*\*Alternative tool\*\*:\s*(.+?)\s*$")
    refusal = re.compile(r"^- We \*\*WILL NOT\*\* (.+?)\s*$")

    current: NonGoal | None = None
    for line in text.splitlines():
        m = heading.match(line)
        if m:
            current = NonGoal(number=int(m.group(1)), title=m.group(2).strip(),
                              refusals=[], alternative="")
            out.append(current)
            continue
        if current is None:
            continue
        m = refusal.match(line)
        if m:
            current.refusals.append(m.group(1).rstrip("."))
            continue
        m = alt.match(line)
        if m and not current.alternative:
            current.alternative = m.group(1)

    if not out:
        raise GenerationError("roadmap: the non-goals document has no numbered sections")

    for ng in out:
        if not ng.alternative:
            # GOVERNANCE.md promises to name the tool that does do it. A board
            # that declines without one leaves the reader stuck.
            raise GenerationError(f"roadmap: non-goal §{ng.number} names no alternative tool")
    return out


def parse_rejected_goals(text: str) -> list[tuple[str, str]]:
    """Reads the goal tree's 'Goals deliberately NOT set' table."""
    out: list[tuple[str, str]] = []
    in_section = False
    for line in text.splitlines():
        if line.startswith("## Goals deliberately NOT set"):
            in_section = True
            continue
        if in_section and line.startswith("## "):
            break
        if not in_section or not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < 2 or cells[0] in ("Not a goal", "") or set(cells[0]) <= set("-: "):
            continue
        out.append((cells[0], cells[1]))

    if not out:
        raise GenerationError("roadmap: the goal tree records no rejected goals")
    return out


def parse_inputs(path: str | None) -> list[Input]:
    """Reads community roadmap input.

    The tracker is not reachable from every machine that builds the docs, so the
    input arrives as a JSON file the CI job fetches. No file means no input,
    which is a real state and not an error.
    """
    if not path or not os.path.exists(path):
        return []

    with open(path, encoding="utf-8") as f:
        raw = json.load(f)

    out: list[Input] = []
    for item in raw:
        disposition = (item.get("disposition") or DISPOSITION_DEFAULT).strip()
        if not any(p.match(disposition) for p in DISPOSITION_PATTERNS):
            raise GenerationError(
                f"roadmap: input #{item.get('number')} has disposition {disposition!r}, "
                "which is not one of: under consideration, accepted as SPEC <id>, "
                "declined — non-goal §<n>, declined — <reason>"
            )
        ticks = int(item.get("ticks", 0))
        if disposition.lower() == DISPOSITION_DEFAULT and ticks > MAX_TICKS_UNDER_CONSIDERATION:
            raise GenerationError(
                f"roadmap: input #{item.get('number')} has been under consideration "
                f"for {ticks} ticks; decide it"
            )
        out.append(Input(number=int(item["number"]), title=item["title"],
                         disposition=disposition, ticks=ticks))

    out.sort(key=lambda i: (-int(raw[[x["number"] for x in raw].index(i.number)].get("reactions", 0)), i.number))
    return out


# A phase whose only unfinished work is blocked is not the phase being worked
# on. Calling it current would tell a reader we are busy with something nobody
# can move, which is the opposite of what a roadmap is for — the blocked specs
# still appear, with `blocked` beside them.
MOVABLE = ("planned", "in progress", "partial")


def current_and_next(phases: list[Phase], progress: dict[str, str]) -> tuple[Phase, Phase | None]:
    """The current phase is the earliest with unfinished work somebody can move."""
    for i, phase in enumerate(phases):
        if any(progress.get(s.spec_id, "planned") in MOVABLE for s in phase.specs):
            return phase, (phases[i + 1] if i + 1 < len(phases) else None)
    return phases[-1], None


# --- rendering -------------------------------------------------------------


def render(phases, non_goals, rejected, inputs, progress) -> str:
    current, upcoming = current_and_next(phases, progress)

    b: list[str] = []
    w = b.append

    w(GENERATED_MARKER)
    w("---")
    w("title: Roadmap")
    w("sidebar_position: 10")
    w("---")
    w("")
    w("# Roadmap")
    w("")
    w("What we are building, what is next, and — third on this page on purpose — what we are")
    w("deliberately not building. Most roadmap questions turn out to be that last one.")
    w("")
    w("**There are no dates on this page.** Phase durations exist in our planning documents as")
    w("estimates. Published as commitments they would generate one kind of feedback and no useful")
    w("planning, so they are not published.")
    w("")

    w("## What we are working on now")
    w("")
    w(f"**Phase {current.number} — {current.theme}** · goal {current.goal}")
    w("")
    w("| Spec | What it is | Placement | Status |")
    w("|---|---|---|---|")
    for s in current.specs:
        status = progress.get(s.spec_id, "planned")
        w(f"| {s.spec_id} | {s.title} | `{s.placement}` | {status} |")
    w("")

    blocked = [(p, s) for p in phases for s in p.specs
               if progress.get(s.spec_id, "planned") == "blocked"]
    if blocked:
        w("### Blocked")
        w("")
        w("Work that is specified and cannot move until something outside the code changes — a")
        w("decision, a credential, a piece of infrastructure, or a person. It is listed rather than")
        w("quietly omitted, because a roadmap that shows only what is moving is a roadmap that")
        w("cannot be checked.")
        w("")
        w("| Spec | What it is | Phase |")
        w("|---|---|---|")
        for phase, s in blocked:
            w(f"| {s.spec_id} | {s.title} | {phase.number} |")
        w("")

    w("## What is next")
    w("")
    if upcoming is None:
        w("Phase " + str(current.number) + " is the last planned phase. What follows it is not decided,")
        w("and this page will say so rather than inventing a plan to fill the space.")
    else:
        w(f"**Phase {upcoming.number} — {upcoming.theme}** · goal {upcoming.goal}")
        w("")
        w("| Spec | What it is | Placement |")
        w("|---|---|---|")
        for s in upcoming.specs:
            w(f"| {s.spec_id} | {s.title} | `{s.placement}` |")
    w("")

    w("## What we are deliberately not building")
    w("")
    w("These are permanent. They are not a backlog, they are not waiting for demand, and a")
    w("well-argued request that crosses one is still declined — we will say so, cite the section,")
    w("and name the tool that does do it. Changing any of them needs the charter's §6 amendment")
    w("procedure, not a vote.")
    w("")
    for ng in non_goals:
        w(f"### §{ng.number}. {ng.title}")
        w("")
        for r in ng.refusals:
            w(f"- We will not {r}.")
        w(f"- **Use instead:** {ng.alternative}")
        w("")

    w("## Goals we considered and rejected")
    w("")
    w("Recording these stops them being re-proposed every quarter as though they were new.")
    w("")
    w("| Not a goal | Why |")
    w("|---|---|")
    for name, why in rejected:
        w(f"| {name} | {why} |")
    w("")

    w("## What the community has asked for")
    w("")
    w("Open a **Roadmap input** issue and tell us the *problem*. Reactions tell us what people want;")
    w("they do not decide what gets built — see")
    w("[how input is weighed](https://github.com/lgreene03/gravix-dashboards/blob/main/docs/oss/roadmap-input.md).")
    w("")
    w("Every item carries a disposition, and nothing sits unlabelled. An item may sit")
    w(f"`under consideration` for at most {MAX_TICKS_UNDER_CONSIDERATION} goal reviews; after that it")
    w("is accepted or declined with a reason, because indefinite consideration is a decline nobody")
    w("has to defend.")
    w("")
    if not inputs:
        w("_No roadmap input yet._ Yours would be the first.")
    else:
        w("| Input | What was asked | Disposition |")
        w("|---|---|---|")
        for i in inputs:
            w(f"| #{i.number} | {i.title} | {i.disposition} |")
    w("")

    w("## How this page is made")
    w("")
    w("Generated by `scripts/gen_roadmap_board.py` from")
    w("[`docs/oss/12-goal-tree.md`](https://github.com/lgreene03/gravix-dashboards/blob/main/docs/oss/12-goal-tree.md),")
    w("[`docs/oss/specs/SPEC-INDEX.md`](https://github.com/lgreene03/gravix-dashboards/blob/main/docs/oss/specs/SPEC-INDEX.md)")
    w("and")
    w("[`docs/04-non-goals.md`](https://github.com/lgreene03/gravix-dashboards/blob/main/docs/04-non-goals.md),")
    w("on every commit.")
    w("")
    w("`make roadmap-check` fails when this page differs from a fresh generation, so a stale roadmap")
    w("is a red build rather than an oversight somebody discovers months later. Nothing on this page")
    w("is typed by hand; to change it, change the document it comes from.")
    w("")

    return "\n".join(b) + "\n"


def check_no_dates(board: str) -> None:
    for line in board.splitlines():
        # The generated marker and the source links are machinery, not promises.
        if line.startswith(GENERATED_MARKER) or "github.com" in line:
            continue
        m = DATE_PATTERNS.search(line)
        if m:
            raise GenerationError(
                "roadmap: generated board contains a date; phase durations are "
                f"estimates, not commitments (found {m.group(0)!r} in {line.strip()!r})"
            )


def load_progress() -> dict[str, str]:
    """Reads spec status from the register of what has actually been executed.

    A spec is done when its commit is in the history. Reading that from git
    would make the board depend on a clone with history, which the OSS build
    copy does not have — so the status file is the source, and it is written by
    whoever merges the work.
    """
    path = os.path.join(ROOT, "docs", "oss", "spec-status.json")
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--input-json", default=os.path.join(ROOT, "docs", "oss", "roadmap-input.json"))
    ap.add_argument("--check", action="store_true",
                    help="write nothing; fail if the committed board is stale")
    args = ap.parse_args()

    try:
        phases = parse_phases(read(SPEC_INDEX))
        non_goals = parse_non_goals(read(NON_GOALS))
        rejected = parse_rejected_goals(read(GOAL_TREE))
        inputs = parse_inputs(args.input_json)
        board = render(phases, non_goals, rejected, inputs, load_progress())
        check_no_dates(board)
    except GenerationError as e:
        print(e, file=sys.stderr)
        return 1

    if args.check:
        if not os.path.exists(args.out):
            print(f"roadmap: {args.out} does not exist; run `make roadmap-board`", file=sys.stderr)
            return 1
        committed = read(args.out)
        if committed != board:
            import difflib
            sys.stdout.writelines(difflib.unified_diff(
                committed.splitlines(keepends=True), board.splitlines(keepends=True),
                fromfile=args.out, tofile="freshly generated"))
            print("roadmap: the board is stale; run `make roadmap-board`", file=sys.stderr)
            return 1
        print(f"roadmap: {args.out} is current")
        return 0

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(board)
    print(f"roadmap: wrote {args.out} — phase {phases[0].number}..{phases[-1].number}, "
          f"{len(non_goals)} non-goals, {len(rejected)} rejected goals, {len(inputs)} inputs")
    return 0


if __name__ == "__main__":
    sys.exit(main())
