#!/usr/bin/env python3
"""Generate docs/oss/specs/SPEC-INDEX.md from every GRVX-*.md spec header.

The index is derived, never hand-maintained: a spec whose header changes updates
the index on the next run, and a spec that was never written simply does not
appear. Run: python3 scripts/gen_spec_index.py
"""
import re, pathlib, sys, collections

SPECS = pathlib.Path("docs/oss/specs")
OUT = SPECS / "SPEC-INDEX.md"

PHASE_NAMES = {
    7:  ("Open the Core",        "G1", "A stranger can trust the code"),
    8:  ("The Correctness Moat", "G2", "A stranger can trust the numbers"),
    9:  ("Zero-Config Value",    "G3", "Ten minutes, no YAML"),
    10: ("Cost Proof",           "G4", "Verify it yourself"),
    11: ("Interop, Not Lock-in", "G5", "Fits the stack you already have"),
    12: ("The Community Machine","G6", "Strangers become contributors"),
    13: ("The Pro Upgrade Path", "G7", "Paying adds; it never subtracts"),
    14: ("Gravix Cloud",         "G8", "Managed, not captured"),
    15: ("Sustainability",       "G9", "Outlives its founder"),
}

FIELD = re.compile(r"^\|\s*\*\*(?P<k>[^*]+)\*\*\s*\|\s*(?P<v>.*?)\s*\|\s*$")

def parse(path):
    text = path.read_text(encoding="utf-8")
    title = ""
    m = re.search(r"^#\s*SPEC\s+(GRVX-\d+):\s*(.+)$", text, re.M)
    if m:
        title = m.group(2).strip()
    fields = {}
    for line in text.splitlines()[:40]:
        if not line.lstrip().startswith("|"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        # A header row is one or more **Key** | value pairs on the same line.
        if len(cells) % 2 or not cells:
            continue
        for i in range(0, len(cells), 2):
            k, v = cells[i], cells[i + 1]
            if k.startswith("**") and k.endswith("**"):
                fields.setdefault(k.strip("* ").strip(), v)
    return title, fields

def clean(v, maxlen=64):
    v = re.sub(r"`", "", v)
    v = re.sub(r"\s+", " ", v).strip()
    if len(v) > maxlen:
        v = v[: maxlen - 1].rstrip() + "…"
    return v or "—"

def main():
    specs = sorted(SPECS.glob("GRVX-*.md"))
    if not specs:
        sys.exit("no specs found")

    by_phase = collections.defaultdict(list)
    total_days = 0.0
    missing = []

    for p in specs:
        title, f = parse(p)
        sid = f.get("Spec ID", p.stem.split("-")[0] + "-" + p.stem.split("-")[1])
        try:
            phase = int(re.sub(r"[^0-9]", "", f.get("Phase", "0")) or 0)
        except ValueError:
            phase = 0
        raw_place = clean(f.get("Placement", "—"), 60).lower()
        if raw_place.startswith("core"):
            placement = "core"
        elif raw_place.startswith("boundary"):
            placement = "boundary"
        elif raw_place.startswith("ee"):
            placement = "ee/"
        else:
            placement = "core" if "core" in raw_place else "ee/"
        goal = clean(f.get("Goal", "—"), 28)
        deps = clean(f.get("Depends on", "—"), 34)
        role = clean(f.get("Implementer role", "—"), 26)
        gate = clean(f.get("Readiness Gate", "—"), 16)
        effort = f.get("Effort", "")
        em = re.search(r"([\d.]+)", effort)
        days = float(em.group(1)) if em else 0.0
        total_days += days
        if not gate.startswith("12/12"):
            missing.append((sid, gate))
        by_phase[phase].append(
            dict(sid=sid, title=title, file=p.name, placement=placement,
                 goal=goal, deps=deps, role=role, days=days, gate=gate)
        )

    lines = []
    lines.append("<!-- GENERATED BY scripts/gen_spec_index.py — DO NOT EDIT -->")
    lines.append("# Gravix Horizon 2 — Specification Index\n")
    lines.append(f"**{len(specs)} specifications** across Phases 7-15, "
                 f"totalling **{total_days:.0f} person-days** (~{total_days/5:.0f} person-weeks).\n")
    lines.append("Each spec is a self-contained work order. The implementing agent reads exactly one")
    lines.append("spec plus the files it names in §4 — not the roadmap, not the charter, not the issue")
    lines.append("thread. A spec that cannot be executed from its own contents is defective and returns")
    lines.append("to `senior-engineering-lead` as a `SPEC DEFECT`; the implementer never improvises.\n")
    lines.append("Governing documents: [charter](../00-open-core-charter.md) ·")
    lines.append("[thesis](../01-competitive-thesis.md) · [roster](../10-agent-roster.md) ·")
    lines.append("[loops](../11-agent-loops.md) · [goals](../12-goal-tree.md) ·")
    lines.append("[roadmap](../20-roadmap-horizon-2.md) · [template](_TEMPLATE.md)\n")
    lines.append("---\n")

    lines.append("## Summary by phase\n")
    lines.append("| Phase | Theme | Goal | Specs | Person-days | core | ee/ |")
    lines.append("|---|---|---|---|---|---|---|")
    for ph in sorted(by_phase):
        items = by_phase[ph]
        name, goal, _ = PHASE_NAMES.get(ph, ("—", "—", "—"))
        d = sum(i["days"] for i in items)
        c = sum(1 for i in items if i["placement"] == "core")
        e = sum(1 for i in items if i["placement"] == "ee/")
        b = sum(1 for i in items if i["placement"] == "boundary")
        cc = f"{c}" + (f" (+{b} boundary)" if b else "")
        lines.append(f"| {ph} | {name} | {goal} | {len(items)} | {d:.0f} | {cc} | {e} |")
    lines.append(f"| | **Total** | | **{len(specs)}** | **{total_days:.0f}** | | |\n")
    lines.append("---\n")

    for ph in sorted(by_phase):
        name, goal, theme = PHASE_NAMES.get(ph, ("—", "—", "—"))
        lines.append(f"## Phase {ph} — {name}\n")
        lines.append(f'**Goal:** {goal} · **Theme:** "{theme}"\n')
        lines.append("| Spec | Title | Placement | Goal | Depends on | Role | Days |")
        lines.append("|---|---|---|---|---|---|---|")
        for i in sorted(by_phase[ph], key=lambda x: x["sid"]):
            lines.append(
                f'| [{i["sid"]}]({i["file"]}) | {i["title"]} | `{i["placement"]}` | '
                f'{i["goal"]} | {i["deps"]} | `{i["role"]}` | {i["days"]:.0f} |'
            )
        lines.append("")

    lines.append("---\n")
    lines.append("## Readiness\n")
    if missing:
        lines.append("These specs have not passed the 12-check Spec Readiness Gate "
                     "(`../11-agent-loops.md` §L2) and MUST NOT be dispatched:\n")
        for sid, gate in missing:
            lines.append(f"- **{sid}** — gate: {gate}")
        lines.append("")
    else:
        lines.append("All specs pass the 12-check Spec Readiness Gate "
                     "(`../11-agent-loops.md` §L2) and are dispatchable.\n")

    lines.append("## Dispatch brief\n")
    lines.append("```")
    lines.append("Goal: <the spec's §1 objective, one sentence>")
    lines.append("Role: <the spec's Implementer role>")
    lines.append("Spec: docs/oss/specs/GRVX-<nnn>-<slug>.md")
    lines.append("Read only: the spec, and the files it names in §4")
    lines.append("Exit Criteria: every §7 acceptance criterion passes; §8 output pasted verbatim")
    lines.append("```\n")
    lines.append("Never attach conversation history. See `../11-agent-loops.md` §L3 for why: a")
    lines.append("subagent needing more than a brief and a file list is reporting a spec defect,")
    lines.append("whether or not it says so.")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}: {len(specs)} specs, {total_days:.0f} person-days, "
          f"{len(missing)} not gate-passed")

if __name__ == "__main__":
    main()
