#!/usr/bin/env python3
"""Generate the free-tier and pricing pages from docs/oss/boundary.yaml.

GRVX-1312 §5.3. Neither page is hand-maintained, and that is the whole point:
a capability cannot be moved to `ee/` without appearing on the paid list and
disappearing from the free list on the very next commit. There is no path by
which these pages quietly stop matching the code.

`make pricing-check` regenerates and diffs, so a stale page fails CI.
"""

import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
BOUNDARY = ROOT / "docs" / "oss" / "boundary.yaml"
PRICING = ROOT / "docs-site" / "docs" / "pricing.md"
FREE = ROOT / "docs-site" / "docs" / "what-stays-free.md"

GENERATED = "<!-- GENERATED by scripts/gen_pricing_page.py — do not edit; run `make pricing-page` -->"

# GRVX-1312 §5.3 asks for the GENERATED marker on the *first* line. It goes after
# the frontmatter instead, because a frontmatter block is only recognised when the
# opening `---` is the very first thing in the file — a leading comment turns the
# block into body text and the page loses its title and sidebar position.
# docs-site/docs/roadmap.md puts the marker first and so probably has that defect
# already; it is not this spec's file to change. Nothing catches it either way,
# because no workflow builds the docs site. See SD-053.

# Charter §2 section titles, used as the "area" grouping. Derived from the
# charter's own headings rather than invented here, so a reader can follow a
# line on the page back to the clause that put it there.
AREAS = {
    "§2.1": "The product itself",
    "§2.2": "Running Gravix for other people",
    "§2.3": "Borderline cases, decided in advance",
}

# GRVX-1312 §5.2, verbatim. Reproduced as a literal because the spec requires it
# word for word and TestCommitmentsVerbatim checks it against the spec file.
COMMITMENTS = """We will never charge for:

  - reading your own data, by API, by SQL, or by export;
  - getting your data out, in an open format, at any volume;
  - authentication, RBAC, two-factor, TLS, or audit logging;
  - the number of services, hosts, seats, or events you monitor;
  - how long you keep your own data on your own disk;
  - the correctness of any number Gravix reports.

These are not current pricing decisions. Charter §7.3 makes them structural: a
feature that fails the Crippleware Test cannot be sold, and a capability already
released under Apache-2.0 can never be taken back.

In Phase 7 we removed the paywall from five features that were already shipping
behind one — the public metrics API, custom dashboards, scheduled exports,
per-tenant rate limiting, and the audit log. That cost us revenue we already had.
It is the clearest evidence we can offer that the rule is real."""


def load():
    caps = yaml.safe_load(BOUNDARY.read_text())["capabilities"]
    return (
        [c for c in caps if c["placement"] == "core"],
        [c for c in caps if c["placement"] == "ee"],
    )


def area_of(cap):
    """The charter section a capability was placed by, as a display heading."""
    primary = cap["charter_ref"].split(",")[0].strip()
    return AREAS.get(primary, primary)


def group(caps):
    out = {}
    for cap in caps:
        out.setdefault(area_of(cap), []).append(cap)
    return out


def render_free_entries(caps):
    lines = []
    for area, entries in group(caps).items():
        lines.append(f"### {area}\n")
        for cap in sorted(entries, key=lambda c: c["name"]):
            lines.append(f"- **{cap['name']}** — {cap['rationale']}")
        lines.append("")
    return "\n".join(lines)


def free_page(core):
    return f"""---
title: What stays free
sidebar_position: 9
---
{GENERATED}

# What stays free, forever

Every capability below is Apache-2.0 and will remain so. This page is generated from
[`docs/oss/boundary.yaml`](https://github.com/lgreene03/gravix-dashboards/blob/main/docs/oss/boundary.yaml),
the machine-readable map the code is checked against, so it cannot drift from what Gravix
actually does — if a capability moved to the paid tier, it would vanish from this page on the
same commit.

**{len(core)} capabilities.** That is the whole list, not a summary of it.

{render_free_entries(core)}
## Why this list can only grow

Charter §7.3 makes it structural rather than a pricing decision. A capability already released
under Apache-2.0 cannot be taken back — the licence does not permit it — and a feature that
fails the [Crippleware Test](https://github.com/lgreene03/gravix-dashboards/blob/main/docs/oss/00-open-core-charter.md)
cannot be sold in the first place.

In Phase 7, five capabilities that were already shipping behind a paywall were moved here:
the public metrics API, custom dashboards, scheduled exports, per-tenant rate limiting, and the
audit log. That cost revenue the project already had.

See [Pricing](pricing.md) for what Pro adds, and why none of it is a limit on anything above.
"""


def pricing_page(core, ee):
    free_section = render_free_entries(core)

    paid = []
    for cap in sorted(ee, key=lambda c: c["name"]):
        paid.append(f"- **{cap['name']}** — {cap['rationale']}")
        if cap.get("note"):
            paid.append(f"  <br/>*{cap['note']}*")
    paid_section = "\n".join(paid)

    return f"""---
title: Pricing
sidebar_position: 10
---
{GENERATED}

# Pricing

The free list comes first, and it is the longest section on this page. That ordering is
deliberate: a pricing page that opens with tiers and buries the free tier is optimised for
conversion, and this one is optimised for someone deciding whether to trust the project.

## Everything below is free forever

{len(core)} capabilities, generated from
[`boundary.yaml`](https://github.com/lgreene03/gravix-dashboards/blob/main/docs/oss/boundary.yaml).
The dedicated [What stays free](what-stays-free.md) page carries the same list.

{free_section}
## What we will never charge for

```
{COMMITMENTS}
```

## What Gravix Pro adds

{len(ee)} capabilities, each solving a problem that appears at a scale a single team does not
reach. None of them is a limit imposed on anything in the free list.

{paid_section}

## Pricing

**No plans are defined yet, and this page will not invent them.**

Packaging and prices come from GRVX-1305, which is blocked: it depends on GRVX-1304, which
needs a new core extension point, and that is a design-tier change requiring **two maintainer
approvals** under `GOVERNANCE.md`. The project currently has one maintainer. RFC 0002 is drafted
and open.

What is already fixed, and will not change when plans are defined:

- The unit is **events ingested**, flat. No cardinality-driven pricing — Gravix's own criticism
  of cardinality billing applies to Gravix.
- Every plan will state its included volume and its overage rate **before** any signup step.
- No plan will impose a limit on any capability in the free list above.
- The full price will be on this page. No "contact us" for a listed tier, and no email gate.

## What happens if you stop paying

The core is unaffected. It does not phone home, it does not check a licence, and it does not
change behaviour when a subscription lapses — `ee/` is a separate directory the core is proven to
build without.

Your `ee/` configuration stays readable and exportable, and **nothing is deleted**. A lapsed
subscription removes access to `ee/` capabilities; it does not hold your data hostage, because
getting your data out is on the never-charge list above.

## Why the free tier is not a trial

A trial is a full product with a timer. This is a smaller product with no timer, and the
difference is enforced rather than promised:

- [The charter](https://github.com/lgreene03/gravix-dashboards/blob/main/docs/oss/00-open-core-charter.md)
  §7.1 requires the core to build, test and run with `ee/` physically deleted. CI does exactly
  that on every pull request.
- The **Crippleware Test** (§7.3) asks five questions of any proposed paid feature. All five must
  be "no". "People would pay for it" is never sufficient.
- GRVX-710 applied that test retroactively and moved five already-paid features into the free
  tier. The record for each is in `boundary.yaml` under `Gate removed by GRVX-710`.

There is no upsell anywhere in the product. An `ee/` capability you have not bought is **absent**,
not locked, not greyed out, and not advertised — charter §7.4, checked by a test.
"""


def main():
    core, ee = load()
    pages = {FREE: free_page(core), PRICING: pricing_page(core, ee)}

    if "--check" in sys.argv:
        stale = []
        for path, want in pages.items():
            have = path.read_text() if path.exists() else ""
            if have != want:
                stale.append(path.relative_to(ROOT))
        if stale:
            print("stale generated page(s): " + ", ".join(str(p) for p in stale))
            print("run `make pricing-page`")
            return 1
        print("pricing pages: current")
        return 0

    for path, text in pages.items():
        path.write_text(text)
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
