// Copyright 2026 The Gravix Authors
// SPDX-License-Identifier: Apache-2.0

package governance

import (
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// GRVX-1312. The pricing page is where the charter is easiest to violate, so its
// constraints are the spec. These check the nine acceptance criteria that do not
// need ee/packaging — which is blocked behind GRVX-1305 and, through it, SD-040.
// AC-6, AC-7 and AC-10 need plan definitions that do not exist yet; AC-12 is
// deliberately not implemented (see SD-053). Nothing here asserts a price,
// because no price has been decided.

func pricingPage(t *testing.T) string { return repoFile(t, "docs-site", "docs", "pricing.md") }
func freePage(t *testing.T) string    { return repoFile(t, "docs-site", "docs", "what-stays-free.md") }

// pricingSection returns the body of a `## heading` up to the next `## `.
func pricingSection(page, heading string) string {
	start := strings.Index(page, "## "+heading)
	if start < 0 {
		return ""
	}
	rest := page[start+len("## "+heading):]
	if end := strings.Index(rest, "\n## "); end >= 0 {
		return rest[:end]
	}
	return rest
}

// AC-1. Ordering is the substance: a page that opens with tiers and buries the
// free tier is optimised for conversion rather than for a reader deciding
// whether to trust the project.
func TestFreeSectionFirstAndLargest(t *testing.T) {
	page := pricingPage(t)

	free := strings.Index(page, "## Everything below is free forever")
	paid := strings.Index(page, "## What Gravix Pro adds")
	price := strings.Index(page, "## Pricing\n")

	if free < 0 || paid < 0 {
		t.Fatal("pricing page is missing the free or the paid section")
	}
	if free > paid {
		t.Error("the paid section comes before the free one")
	}
	if price >= 0 && free > price {
		t.Error("the Pricing section comes before the free list")
	}

	freeLen := len(pricingSection(page, "Everything below is free forever"))
	paidLen := len(pricingSection(page, "What Gravix Pro adds"))
	if freeLen <= paidLen {
		t.Errorf("free section is %d bytes and the paid section is %d; the free one must be longest",
			freeLen, paidLen)
	}
}

// AC-2. Both pages come from boundary.yaml, so neither can be edited into
// disagreeing with the code.
func TestPagesGeneratedFromBoundary(t *testing.T) {
	for _, page := range []string{pricingPage(t), freePage(t)} {
		if !strings.Contains(page, "GENERATED by scripts/gen_pricing_page.py") {
			t.Error("page is missing its GENERATED marker; it may have been hand-edited")
		}
	}

	// Every core capability by name must appear on the free page, and every ee
	// capability must not.
	core, ee := boundaryCaps(t)
	free := freePage(t)
	for _, name := range core {
		if !strings.Contains(free, name) {
			t.Errorf("free page omits the core capability %q", name)
		}
	}
	for _, name := range ee {
		if strings.Contains(free, name) {
			t.Errorf("free page lists %q, which is placement: ee", name)
		}
	}
}

// AC-3. A stale page fails, which is what makes AC-2 mean anything.
func TestStalePricingPageFails(t *testing.T) {
	root := repoRoot(t)
	script := filepath.Join(root, "scripts", "gen_pricing_page.py")
	target := filepath.Join(root, "docs-site", "docs", "what-stays-free.md")

	original, err := os.ReadFile(target)
	if err != nil {
		t.Fatalf("reading the free page: %v", err)
	}
	t.Cleanup(func() { _ = os.WriteFile(target, original, 0o644) })

	if err := os.WriteFile(target, append(original, []byte("\nhand-edited\n")...), 0o644); err != nil {
		t.Fatalf("staling the page: %v", err)
	}

	cmd := exec.Command("python3", script, "--check")
	cmd.Dir = root
	out, err := cmd.CombinedOutput()
	if err == nil {
		t.Errorf("--check passed on a hand-edited page; it must fail:\n%s", out)
	}
	if !strings.Contains(string(out), "what-stays-free.md") {
		t.Errorf("the failure does not name the stale file:\n%s", out)
	}
}

// AC-5. The commitments are the load-bearing sentences on the page. Checked
// against the spec itself so the page cannot soften them.
func TestCommitmentsVerbatim(t *testing.T) {
	page := pricingPage(t)
	spec := repoFile(t, "docs", "oss", "specs", "GRVX-1312-pro-packaging-and-free-tier-page.md")

	for _, line := range []string{
		"We will never charge for:",
		"reading your own data, by API, by SQL, or by export;",
		"getting your data out, in an open format, at any volume;",
		"authentication, RBAC, two-factor, TLS, or audit logging;",
		"the number of services, hosts, seats, or events you monitor;",
		"how long you keep your own data on your own disk;",
		"the correctness of any number Gravix reports.",
		"That cost us revenue we already had.",
	} {
		if !strings.Contains(spec, line) {
			t.Fatalf("this test is checking a line the spec does not contain: %q", line)
		}
		if !strings.Contains(page, line) {
			t.Errorf("pricing page is missing the commitment line: %q", line)
		}
	}
}

// AC-8. Charter §7.4. An ee/ capability without a licence is absent, not teased.
func TestNoUpsellInProduct(t *testing.T) {
	root := repoRoot(t)
	// Word-bounded. The spec's §8 grep is not, and "Go produced no ..." in
	// dashboards/lib/tco.test.js:117 contains "go pro" as a substring — running
	// that command verbatim reports 1 where the spec expects 0. See SD-053.
	upsell := regexp.MustCompile(`(?i)\bupgrade to pro\b|\bgo pro\b|\bunlock this\b|\bpremium feature\b|\bstart your trial\b`)

	err := filepath.Walk(filepath.Join(root, "dashboards"), func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}
		body, readErr := os.ReadFile(path)
		if readErr != nil {
			return readErr
		}
		for i, line := range strings.Split(string(body), "\n") {
			if upsell.MatchString(line) {
				rel, _ := filepath.Rel(root, path)
				t.Errorf("charter §7.4: upsell element found at %s:%d", rel, i+1)
			}
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walking dashboards/: %v", err)
	}
}

// AC-9. No core capability may gain a limit introduced by packaging. There is no
// packaging yet, so this asserts the boundary file itself carries no limit
// vocabulary on a core entry — and will keep asserting it once plans exist.
func TestNoArtificialLimitsOnCore(t *testing.T) {
	root := repoRoot(t)
	raw, err := os.ReadFile(filepath.Join(root, "docs", "oss", "boundary.yaml"))
	if err != nil {
		t.Fatalf("reading boundary.yaml: %v", err)
	}

	limit := regexp.MustCompile(`(?i)\b(max_|quota|seat_limit|retention_cap|throttle)\b`)
	if limit.Match(raw) {
		t.Error("boundary.yaml contains limit vocabulary; charter §7.4 forbids an artificial " +
			"limit in the core to make a tier look better")
	}
}

// AC-11. No email gate, and no "contact us" standing in for a number.
func TestNoEmailGateOnPricing(t *testing.T) {
	page := pricingPage(t)
	gate := regexp.MustCompile(`(?i)<input[^>]*type=["']email|enter your email|contact us for pricing`)
	if gate.MatchString(page) {
		t.Error("the pricing page gates its numbers behind an email or a contact form")
	}
}

// boundaryCaps returns the display names of core and ee capabilities.
func boundaryCaps(t *testing.T) (core, ee []string) {
	t.Helper()
	raw := repoFile(t, "docs", "oss", "boundary.yaml")

	var name, placement string
	flush := func() {
		if name == "" {
			return
		}
		if placement == "ee" {
			ee = append(ee, name)
		} else if placement == "core" {
			core = append(core, name)
		}
		name, placement = "", ""
	}
	for _, line := range strings.Split(raw, "\n") {
		trimmed := strings.TrimSpace(line)
		switch {
		case strings.HasPrefix(trimmed, "- id:"):
			flush()
		case strings.HasPrefix(trimmed, "name:"):
			name = strings.TrimSpace(strings.TrimPrefix(trimmed, "name:"))
		case strings.HasPrefix(trimmed, "placement:"):
			placement = strings.TrimSpace(strings.TrimPrefix(trimmed, "placement:"))
		}
	}
	flush()

	if len(core) == 0 || len(ee) == 0 {
		t.Fatalf("parsed %d core and %d ee capabilities from boundary.yaml; expected both",
			len(core), len(ee))
	}
	return core, ee
}

// AC-4. The consequence that makes the whole apparatus worth having: a
// capability cannot be moved to ee/ without appearing on the paid list and
// disappearing from the free list on the next commit. Proven by actually moving
// one and regenerating, then restoring.
func TestBoundaryChangeUpdatesBothLists(t *testing.T) {
	root := repoRoot(t)
	boundary := filepath.Join(root, "docs", "oss", "boundary.yaml")
	freePath := filepath.Join(root, "docs-site", "docs", "what-stays-free.md")
	pricingPath := filepath.Join(root, "docs-site", "docs", "pricing.md")

	originals := map[string][]byte{}
	for _, p := range []string{boundary, freePath, pricingPath} {
		body, err := os.ReadFile(p)
		if err != nil {
			t.Fatalf("reading %s: %v", p, err)
		}
		originals[p] = body
	}
	t.Cleanup(func() {
		for p, body := range originals {
			_ = os.WriteFile(p, body, 0o644)
		}
	})

	// Pick a real core capability and move it, rather than inventing one — an
	// invented entry would not prove the generator reads the same file the
	// boundary checker does.
	const moved = "ingestion-http"
	src := string(originals[boundary])
	idx := strings.Index(src, "- id: "+moved)
	if idx < 0 {
		t.Fatalf("boundary.yaml no longer has %q; pick another capability", moved)
	}
	rest := src[idx:]
	relPlacement := strings.Index(rest, "placement: core")
	if relPlacement < 0 {
		t.Fatalf("%q is not placement: core", moved)
	}
	mutated := src[:idx] + strings.Replace(rest, "placement: core", "placement: ee", 1)
	if err := os.WriteFile(boundary, []byte(mutated), 0o644); err != nil {
		t.Fatalf("mutating boundary.yaml: %v", err)
	}

	cmd := exec.Command("python3", filepath.Join(root, "scripts", "gen_pricing_page.py"))
	cmd.Dir = root
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("regenerating: %v\n%s", err, out)
	}

	const name = "HTTP fact ingestion"
	newFree, err := os.ReadFile(freePath)
	if err != nil {
		t.Fatalf("re-reading the free page: %v", err)
	}
	if strings.Contains(string(newFree), name) {
		t.Errorf("%q moved to ee but is still on the free page", name)
	}

	newPricing, err := os.ReadFile(pricingPath)
	if err != nil {
		t.Fatalf("re-reading the pricing page: %v", err)
	}
	if !strings.Contains(pricingSection(string(newPricing), "What Gravix Pro adds"), name) {
		t.Errorf("%q moved to ee but did not appear in the paid section", name)
	}
}
